version: '3'

services:

  image_server:
    build: .
    depends_on:
      - 'database'
    ports:
      - '3007:3007'

  database:
    build: db/
    image: mysql:5.7
    ports:
      - '3306:3306'

    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: products